# Generated by Django 3.1.12 on 2024-12-02 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sssapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='result',
            field=models.CharField(max_length=10),
        ),
    ]
